[package]
name = "asteroid"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "asteroid"
path = "src/main.rs"

[dependencies]
asteroid-settings = { path = "../asteroid-settings" }
asteroid-workspace = { path = "../asteroid-workspace" }
gpui-kit = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
