[package]
name = "cincel-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-channel = { workspace = true }
dirs = { workspace = true }
jsonc-parser = { workspace = true }
notify = { workspace = true }
cincel-watch = { path = "../cincel-watch" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
